name: Test & Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup GTest
      uses: actions/checkout@v3
      with:
        repository: google/googletest
        path: 3rdparty/gtest
        
    - name: Test
      run: |
        mkdir build
        cd build
        cmake .. -DTEST=on -DGITHUB_ACTIONS=on
        make
        ../tests/bin/encoder_test
        ../tests/bin/logger_test
